"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { AuthForm } from "../components/AuthForm";
import { UserBar } from "../components/UserBar";
import { AppLogo } from "../components/AppLogo";
type Board = { id: string; title: string; created_at: string };
export default function Home() { const [boards, setBoards] = useState<Board[]>([]); const [title, setTitle] = useState(""); const [error, setError] = useState(""); const [authenticated, setAuthenticated] = useState(false); const [checkingSession, setCheckingSession] = useState(true);
  async function load() { if (!supabase) { setError("Configure as variáveis do Supabase."); return; } const { data, error } = await supabase.from("boards").select("id,title,created_at").order("created_at", { ascending: false }); if (error) setError(error.message); else setBoards(data ?? []); }
  useEffect(() => { if (!supabase) { setCheckingSession(false); return; } void supabase.auth.getUser().then(({ data }) => { const loggedIn = Boolean(data.user); setAuthenticated(loggedIn); setCheckingSession(false); if (loggedIn) void load(); }); }, []);
  async function createBoard() { if (!supabase || !title.trim()) return; const user = await supabase.auth.getUser(); if (!user.data.user) { setError("Entre na sua conta para criar um board."); return; } const { data, error } = await supabase.from("boards").insert({ title: title.trim(), owner_id: user.data.user.id }).select("id").single(); if (error) { setError(error.message); return; } const columns = ["O que deu certo", "O que não deu certo", "Melhorar", "Planos de Ação"].map((name, position) => ({ board_id: data.id, title: name, position: position + 1 })); const result = await supabase.from("board_columns").insert(columns); if (result.error) setError(result.error.message); else window.location.href = `/board/${data.id}`; }
  const [query, setQuery] = useState(""); const filteredBoards = useMemo(() => boards.filter(board => board.title.toLowerCase().includes(query.toLowerCase().trim())), [boards, query]);
  return <main className="shell home-page"><UserBar />{!authenticated && <AppLogo />}<h1>{authenticated ? "Retrospectivas" : "Entre no R-Retro"}</h1>{checkingSession ? <p className="hint">Verificando sessão...</p> : !authenticated ? <AuthForm onAuthenticated={() => window.location.reload()} /> : <><header className="home-header"><div><p className="section-label">Seus boards</p><p className="hint">Escolha uma retrospectiva para continuar.</p></div><span className="count-pill">{boards.length} {boards.length === 1 ? "board" : "boards"}</span></header>{error && <p className="error">{error}</p>}<div className="create-board form"><label htmlFor="new-board">Criar novo board</label><div><input id="new-board" value={title} onChange={e => setTitle(e.target.value)} onKeyDown={e => { if (e.key === "Enter") void createBoard(); }} placeholder="Nome da nova retrospectiva" /><button onClick={() => void createBoard()}>Criar board</button></div></div><div className="board-search"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar nos seus boards" aria-label="Buscar nos seus boards" /></div>{filteredBoards.length === 0 ? <div className="empty-state home-empty"><strong>{query ? `Nenhum board encontrado para “${query}”.` : "Você ainda não criou nenhum board."}</strong>{query && <button className="secondary-button" onClick={() => setQuery("")}>Limpar busca</button>}</div> : <section className="boards">{filteredBoards.map(board => <a className="board-link" href={`/board/${board.id}`} key={board.id}><span className="board-name">{board.title}</span><span>Abrir board <span aria-hidden="true">→</span></span></a>)}</section>}</>}</main>; }
