"use client";
import { FormEvent, useState } from "react";
import { supabase } from "../lib/supabase";

export function AuthForm({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [mode, setMode] = useState<"login" | "signup" | "recovery">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!supabase) { setMessage("Configure as variáveis do Supabase."); return; } setLoading(true); setMessage(""); const result = mode === "recovery" ? await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }) : mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); setLoading(false); if (result.error) setMessage(result.error.message); else if (mode === "recovery") setMessage("Enviamos um link de recuperação para seu e-mail."); else if (mode === "signup" && !("session" in result.data && result.data.session)) setMessage("Cadastro criado. Verifique seu e-mail para confirmar a conta."); else onAuthenticated(); }
  return <div className="auth-card"><h2>{mode === "login" ? "Entrar" : mode === "signup" ? "Criar conta" : "Recuperar senha"}</h2>{mode === "recovery" && <p className="hint">Informe seu e-mail para receber um link de recuperação.</p>}<form className="form" onSubmit={submit}><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="seu@email.com" /><>{mode !== "recovery" && <input type="password" required minLength={6} value={password} onChange={e => setPassword(e.target.value)} placeholder="Senha (mínimo 6 caracteres)" />}</><button disabled={loading}>{loading ? "Aguarde..." : mode === "login" ? "Entrar" : mode === "signup" ? "Cadastrar" : "Enviar link"}</button></form>{message && <p className="hint">{message}</p>}<div className="auth-links">{mode === "login" && <button className="text-button" onClick={() => { setMode("recovery"); setMessage(""); }}>Esqueci minha senha</button>}<button className="text-button" onClick={() => { setMode(mode === "login" || mode === "recovery" ? "signup" : "login"); setMessage(""); }}>{mode === "signup" ? "Já tenho uma conta" : "Ainda não tenho conta"}</button>{mode === "recovery" && <button className="text-button" onClick={() => { setMode("login"); setMessage(""); }}>Voltar para entrar</button>}</div></div>;
}
