"use client";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
export function BoardTimer({ boardId }: { boardId: string }) { const [seconds, setSeconds] = useState(300); const [endsAt, setEndsAt] = useState<string | null>(null); const [running, setRunning] = useState(false); const [canControl, setCanControl] = useState(false); const [minutes, setMinutes] = useState("5");
  async function load() { if (!supabase) return; const result = await supabase.from("board_timers").select("duration_seconds,ends_at,running").eq("board_id", boardId).maybeSingle(); if (!result.error && result.data) { setSeconds(result.data.duration_seconds); setEndsAt(result.data.ends_at); setRunning(result.data.running); } }
  useEffect(() => { void load(); if (!supabase) return; void Promise.all([supabase.auth.getUser(), supabase.from("boards").select("owner_id").eq("id", boardId).maybeSingle()]).then(([user, board]) => setCanControl(Boolean(user.data.user && board.data?.owner_id === user.data.user.id))); const channel = supabase.channel(`timer-${boardId}`).on("postgres_changes", { event: "*", schema: "public", table: "board_timers", filter: `board_id=eq.${boardId}` }, () => void load()).subscribe(); return () => { void supabase?.removeChannel(channel); }; }, [boardId]);
  useEffect(() => { const id = window.setInterval(() => { if (running && endsAt) setSeconds(Math.max(0, Math.ceil((new Date(endsAt).getTime() - Date.now()) / 1000))); }, 500); return () => window.clearInterval(id); }, [running, endsAt]);
  async function start() { if (!supabase || !canControl) return; const duration = Math.max(10, Number(minutes) * 60); const result = await supabase.from("board_timers").upsert({ board_id: boardId, duration_seconds: duration, ends_at: new Date(Date.now() + duration * 1000).toISOString(), running: true, updated_at: new Date().toISOString() }); if (result.error) console.error(result.error); }
  async function stop() { if (!supabase || !canControl) return; await supabase.from("board_timers").update({ running: false, ends_at: null, updated_at: new Date().toISOString() }).eq("board_id", boardId); }
  const display = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  return <div className="timer"><strong>⏱ {display}</strong>{canControl && <><input aria-label="Duração em minutos" type="number" min="1" max="120" value={minutes} onChange={e => setMinutes(e.target.value)} /><button onClick={() => void start()}>Iniciar</button><button onClick={() => void stop()}>Parar</button></>}</div>; }
