"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";
export function BoardSettings({ boardId }: { boardId: string }) { const router = useRouter(); const ref = useRef<HTMLDivElement>(null); const [open, setOpen] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false); const [allowed, setAllowed] = useState(false); const [title, setTitle] = useState(""); const [columns, setColumns] = useState<{ id: string; title: string }[]>([]); const [minutes, setMinutes] = useState("5"); const [message, setMessage] = useState("");
  async function load() { if (!supabase) return; const user = await supabase.auth.getUser(); if (!user.data.user) return; const profile = await supabase.from("profiles").select("role").eq("id", user.data.user.id).maybeSingle(); const board = await supabase.from("boards").select("title,owner_id").eq("id", boardId).maybeSingle(); const canEdit = Boolean(board.data?.owner_id === user.data.user.id || (profile.data?.role === "gestor" && (await supabase.from("board_invites").select("id").eq("board_id", boardId).eq("email", user.data.user.email?.toLowerCase() ?? "").maybeSingle()).data)); setAllowed(canEdit); setTitle(board.data?.title ?? ""); const result = await supabase.from("board_columns").select("id,title").eq("board_id", boardId).order("position"); setColumns(result.data ?? []); }
  useEffect(() => { void load(); const close = (event: MouseEvent) => { if (open && ref.current && !ref.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [boardId, open]);
  async function save() { if (!supabase || !allowed) return; const board = await supabase.from("boards").update({ title }).eq("id", boardId); if (board.error) { setMessage(board.error.message); return; } for (const column of columns) { const result = await supabase.from("board_columns").update({ title: column.title }).eq("id", column.id); if (result.error) { setMessage(result.error.message); return; } } const timer = await supabase.from("board_timers").upsert({ board_id: boardId, duration_seconds: Math.max(1, Number(minutes)) * 60, running: false, ends_at: null, updated_at: new Date().toISOString() }); if (timer.error) { setMessage(timer.error.message); return; } setMessage("Configurações salvas."); }
  async function deleteBoard() { if (!supabase || !allowed) return; const result = await supabase.from("boards").delete().eq("id", boardId); if (result.error) setMessage(result.error.message); else router.push("/"); }
  if (!allowed) return null; return <div className="settings" ref={ref}><button className="secondary-button" onClick={() => { setOpen(!open); setConfirmDelete(false); }}>⚙ Configurações</button>{open && <div className="settings-panel"><h2>Configurações do board</h2><label>Título<input value={title} onChange={e => setTitle(e.target.value)} /></label><label>Timer padrão (minutos)<input type="number" min="1" max="120" value={minutes} onChange={e => setMinutes(e.target.value)} /></label>{columns.map((column, index) => <label key={column.id}>Coluna {index + 1}<input value={column.title} onChange={e => setColumns(columns.map(item => item.id === column.id ? { ...item, title: e.target.value } : item))} /></label>)}<button onClick={() => void save()}>Salvar configurações</button>{message && <p className="hint">{message}</p>}<hr />{confirmDelete ? <div className="delete-confirm"><p>Excluir este board e todos os seus cards?</p><button className="danger-button" onClick={() => void deleteBoard()}>Confirmar exclusão</button><button className="text-button" onClick={() => setConfirmDelete(false)}>Cancelar</button></div> : <button className="delete-button" onClick={() => setConfirmDelete(true)}>Excluir board</button>}</div>}</div>; }
