"use client";
import { useEffect, useRef, useState } from "react";
import { supabase } from "../lib/supabase";

type Invite = { id: string; email: string };
export function SharePopover({ boardId }: { boardId: string }) {
  const ref = useRef<HTMLDivElement>(null); const [open, setOpen] = useState(false); const [owner, setOwner] = useState(false); const [email, setEmail] = useState(""); const [invites, setInvites] = useState<Invite[]>([]); const [message, setMessage] = useState("");
  async function load() { if (!supabase) return; const user = await supabase.auth.getUser(); if (!user.data.user) return; const board = await supabase.from("boards").select("owner_id").eq("id", boardId).maybeSingle(); const isOwner = board.data?.owner_id === user.data.user.id; setOwner(isOwner); if (isOwner) { const result = await supabase.from("board_invites").select("id,email").eq("board_id", boardId).order("created_at"); setInvites(result.data ?? []); } }
  useEffect(() => { void load(); }, [boardId]); useEffect(() => { const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []); useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, []);
  async function invite() { if (!supabase || !email.trim()) return; const user = await supabase.auth.getUser(); if (!user.data.user) return; const result = await supabase.from("board_invites").insert({ board_id: boardId, email: email.trim().toLowerCase(), invited_by: user.data.user.id }); if (result.error) setMessage(result.error.message); else { setMessage("Convite registrado com sucesso."); setEmail(""); await load(); } }
  async function remove(id: string) { if (!supabase) return; const result = await supabase.from("board_invites").delete().eq("id", id); if (result.error) setMessage(result.error.message); else await load(); }
  if (!owner) return null;
  return <div className="share-popover" ref={ref}><button className="secondary-button" type="button" aria-haspopup="dialog" aria-expanded={open} onClick={() => { setOpen(value => !value); setMessage(""); }}>Compartilhar</button>{open && <div className="share-panel" role="dialog" aria-label="Compartilhar board"><h2>Compartilhar board</h2><p>Convide participantes pelo e-mail.</p><div className="share-input"><input autoFocus={open} type="email" value={email} onChange={event => setEmail(event.target.value)} onKeyDown={event => { if (event.key === "Enter") void invite(); }} placeholder="E-mail para compartilhar" /><button className="primary-button" type="button" onClick={() => void invite()}>Enviar</button></div>{message && <p className="hint">{message}</p>}{invites.map(item => <div className="invite-row" key={item.id}><span>{item.email}</span><button className="text-button danger" type="button" onClick={() => void remove(item.id)}>Remover</button></div>)}</div>}</div>;
}
