"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
type Profile = { id: string; email: string; role: "master" | "gestor" | "participante"; created_at: string };
export default function AdminUsersPage() { const [profiles, setProfiles] = useState<Profile[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [email, setEmail] = useState(""); const [allowed, setAllowed] = useState(false);
  async function load() { if (!supabase) return; const user = await supabase.auth.getUser(); const profile = user.data.user ? await supabase.from("profiles").select("role").eq("id", user.data.user.id).maybeSingle() : null; if (profile?.data?.role !== "master") { setError("Acesso permitido apenas ao usuário master."); return; } setAllowed(true); const result = await supabase.from("profiles").select("id,email,role,created_at").order("created_at"); if (result.error) setError(result.error.message); else setProfiles(result.data ?? []); }
  useEffect(() => { void load(); }, []);
  async function changeRole(profile: Profile, role: Profile["role"]) { if (!supabase) return; const result = await supabase.from("profiles").update({ role }).eq("id", profile.id); if (result.error) setError(result.error.message); else await load(); }
  async function inviteUser() { if (!supabase || !email.trim()) return; const session = await supabase.auth.getSession(); const result = await fetch("/api/admin/invite-user", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.data.session?.access_token ?? ""}` }, body: JSON.stringify({ email }) }); const body = await result.json(); if (!result.ok) setError(body.error); else { setMessage("Convite enviado por e-mail."); setEmail(""); } }
  return <main className="shell"><a href="/">← Início</a><div className="eyebrow">Administração</div><h1>Usuários</h1>{error && <p className="error">{error}</p>}{message && <p className="hint">{message}</p>}{allowed && <><div className="form admin-create"><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="E-mail do novo usuário" /><button onClick={() => void inviteUser()}>Enviar convite</button></div><section className="admin-table">{profiles.map(profile => <div className="user-row" key={profile.id}><span>{profile.email}</span><select value={profile.role} onChange={e => void changeRole(profile, e.target.value as Profile["role"])}><option value="master">Master</option><option value="gestor">Gestor</option><option value="participante">Participante</option></select></div>)}</section></>}</main>; }
