"use client";
import { use, useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import { UserBar } from "../../../components/UserBar";
type Card = { id: string; column_id: string; content: string }; type Column = { id: string; title: string; position: number; cards: Card[] }; type Invite = { id: string; email: string };
export default function BoardPage({ params }: { params: Promise<{ boardId: string }> }) { const { boardId } = use(params); const [title, setTitle] = useState("Retrospectiva"); const [owner, setOwner] = useState(false); const [columns, setColumns] = useState<Column[]>([]); const [invites, setInvites] = useState<Invite[]>([]); const [error, setError] = useState(""); const [adding, setAdding] = useState<string | null>(null); const [content, setContent] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [editingContent, setEditingContent] = useState(""); const [inviteEmail, setInviteEmail] = useState(""); const [inviteMessage, setInviteMessage] = useState("");
  async function load() { if (!supabase) { setError("Configure as variáveis do Supabase."); return; } const user = await supabase.auth.getUser(); const board = await supabase.from("boards").select("title,owner_id").eq("id", boardId).maybeSingle(); if (board.error) { setError(board.error.message); return; } if (!board.data) { window.location.href = "/"; return; } setTitle(board.data.title); const isOwner = Boolean(user.data.user && board.data.owner_id === user.data.user.id); setOwner(isOwner); if (isOwner) { const invitation = await supabase.from("board_invites").select("id,email").eq("board_id", boardId); setInvites(invitation.data ?? []); } const columnResult = await supabase.from("board_columns").select("id,title,position").eq("board_id", boardId).order("position"); if (columnResult.error) { setError(columnResult.error.message); return; } const columnRows = columnResult.data ?? []; const cardResult = columnRows.length ? await supabase.from("cards").select("id,column_id,content").in("column_id", columnRows.map(column => column.id)) : { data: [], error: null }; if (cardResult.error) { setError(cardResult.error.message); return; } setColumns(columnRows.map(column => ({ ...column, cards: (cardResult.data ?? []).filter(card => card.column_id === column.id) })) as Column[]); }
  useEffect(() => { void load(); const client = supabase; if (!client) return; const channel = client.channel(`board-cards-${boardId}`).on("postgres_changes", { event: "*", schema: "public", table: "cards" }, () => void load()).subscribe(); return () => { void client.removeChannel(channel); }; }, [boardId]);
  async function addCard(columnId: string) { if (!supabase || !content.trim()) return; const result = await supabase.from("cards").insert({ column_id: columnId, content: content.trim() }); if (result.error) setError(result.error.message); else { setContent(""); setAdding(null); await load(); } }
  async function editCard(card: Card) { if (!supabase || !editingContent.trim()) return; const result = await supabase.from("cards").update({ content: editingContent.trim() }).eq("id", card.id); if (result.error) setError(result.error.message); else { setEditingId(null); setEditingContent(""); await load(); } }
  async function deleteCard(card: Card) { if (!supabase || !window.confirm("Excluir este card?")) return; const result = await supabase.from("cards").delete().eq("id", card.id); if (result.error) setError(result.error.message); else await load(); }
  async function invite() { if (!supabase || !inviteEmail.trim()) return; const user = await supabase.auth.getUser(); if (!user.data.user) return; const result = await supabase.from("board_invites").insert({ board_id: boardId, email: inviteEmail.trim().toLowerCase(), invited_by: user.data.user.id }); if (result.error) setInviteMessage(result.error.message); else { setInviteMessage("Convite registrado com sucesso."); setInviteEmail(""); await load(); } }
  async function removeInvite(invite: Invite) { if (!supabase || !window.confirm(`Remover acesso de ${invite.email}?`)) return; const result = await supabase.from("board_invites").delete().eq("id", invite.id); if (result.error) setInviteMessage(result.error.message); else await load(); }
 return <main className="shell"><UserBar /><a href="/">← Todos os boards</a><div className="eyebrow">Board colaborativo</div><h1>{title}</h1>{error && <p className="error">{error}</p>}{owner && <div className="share form"><input type="email" value={inviteEmail} onChange={e => setInviteEmail(e.target.value)} placeholder="E-mail para compartilhar" /><button onClick={() => void invite()}>Compartilhar board</button>{inviteMessage && <p className="hint">{inviteMessage}</p>}{invites.map(inviteItem => <div className="invite-row" key={inviteItem.id}>{inviteItem.email}<button className="text-button" onClick={() => void removeInvite(inviteItem)}>Remover</button></div>)}</div>}<section className="board">{columns.map(column => <article className="column" key={column.id}><h2>{column.title}</h2><div className="cards">{column.cards.map(card => <div className="card" key={card.id}>{editingId === card.id ? <div className="form"><input autoFocus value={editingContent} onChange={e => setEditingContent(e.target.value)} onKeyDown={e => { if (e.key === "Enter") void editCard(card); }} /><button onClick={() => void editCard(card)}>Salvar</button><button onClick={() => { setEditingId(null); setEditingContent(""); }}>Cancelar</button></div> : <><span>{card.content}</span><div className="card-actions"><button className="text-button" onClick={() => { setEditingId(card.id); setEditingContent(card.content); }}>Editar</button><button className="text-button danger" onClick={() => void deleteCard(card)}>Excluir</button></div></>}</div>)}</div>{adding === column.id ? <div className="form"><input autoFocus value={content} onChange={e => setContent(e.target.value)} onKeyDown={e => { if (e.key === "Enter") void addCard(column.id); }} placeholder="Escreva um card" /><button onClick={() => void addCard(column.id)}>Salvar card</button><button onClick={() => setAdding(null)}>Cancelar</button></div> : <button className="add" onClick={() => setAdding(column.id)}>+ adicionar</button>}</article>)}</section></main>; }
