"use client";
import { use, useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import { UserBar } from "../../../components/UserBar";
type Column = { id: string; title: string; position: number; cards: { id: string; content: string }[] };
export default function BoardPage({ params }: { params: Promise<{ boardId: string }> }) { const { boardId } = use(params); const [title, setTitle] = useState("Retrospectiva"); const [columns, setColumns] = useState<Column[]>([]); const [error, setError] = useState(""); const [adding, setAdding] = useState<string | null>(null); const [content, setContent] = useState(""); const [inviteEmail, setInviteEmail] = useState(""); const [inviteMessage, setInviteMessage] = useState("");
  async function load() { if (!supabase) { setError("Configure as variáveis do Supabase."); return; } const board = await supabase.from("boards").select("title").eq("id", boardId).single(); if (board.error) { setError(board.error.message); return; } setTitle(board.data.title); const result = await supabase.from("board_columns").select("id,title,position,cards(id,content)").eq("board_id", boardId).order("position"); if (result.error) setError(result.error.message); else setColumns((result.data ?? []) as Column[]); }
  useEffect(() => { void load(); const client = supabase; if (!client) return; const channel = client.channel(`board-cards-${boardId}`).on("postgres_changes", { event: "*", schema: "public", table: "cards" }, () => void load()).subscribe(); return () => { void client.removeChannel(channel); }; }, [boardId]);
  async function addCard(columnId: string) { if (!supabase || !content.trim()) return; const result = await supabase.from("cards").insert({ column_id: columnId, content: content.trim() }); if (result.error) setError(result.error.message); else { setContent(""); setAdding(null); await load(); } }
  async function invite() { if (!supabase || !inviteEmail.trim()) return; const user = await supabase.auth.getUser(); if (!user.data.user) return; const result = await supabase.from("board_invites").insert({ board_id: boardId, email: inviteEmail.trim().toLowerCase(), invited_by: user.data.user.id }); if (result.error) setInviteMessage(result.error.message); else { setInviteMessage("Convite registrado com sucesso."); setInviteEmail(""); } }
  return <main className="shell"><UserBar /><a href="/">← Todos os boards</a><div className="eyebrow">Board colaborativo</div><h1>{title}</h1>{error && <p className="error">{error}</p>}<div className="share form"><input type="email" value={inviteEmail} onChange={e => setInviteEmail(e.target.value)} placeholder="E-mail para compartilhar" /><button onClick={() => void invite()}>Compartilhar board</button>{inviteMessage && <p className="hint">{inviteMessage}</p>}</div><section className="board">{columns.map(column => <article className="column" key={column.id}><h2>{column.title}</h2><div className="cards">{column.cards?.map(card => <div className="card" key={card.id}>{card.content}</div>)}</div>{adding === column.id ? <div className="form"><input autoFocus value={content} onChange={e => setContent(e.target.value)} onKeyDown={e => { if (e.key === "Enter") void addCard(column.id); }} placeholder="Escreva um card" /><button onClick={() => void addCard(column.id)}>Salvar card</button><button onClick={() => setAdding(null)}>Cancelar</button></div> : <button className="add" onClick={() => setAdding(column.id)}>+ adicionar</button>}</article>)}</section></main>; }
